# Generated by Django 3.2.7 on 2022-01-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('volume', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('email', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('contact', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.IntegerField()),
                ('invested', models.IntegerField()),
                ('profit', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
    ]
